YAML_SYNTAX_ERROR = ... # type: str
YAML_POSITION_DETAILS = ... # type: str
YAML_COMMON_DICT_ERROR = ... # type: str
YAML_COMMON_UNQUOTED_VARIABLE_ERROR = ... # type: str
YAML_COMMON_UNQUOTED_COLON_ERROR = ... # type: str
YAML_COMMON_PARTIALLY_QUOTED_LINE_ERROR = ... # type: str
YAML_COMMON_UNBALANCED_QUOTES_ERROR = ... # type: str
