from typing import *

class Playbook:
    def __init__(self, loader: Optional[Any]) -> None: ...
    @staticmethod
    def load(file_name: str, variable_manager: Optional[Any] = ..., loader: Optional[Any] = ...) -> Playbook: ...
    def _load_playbook_data(self, file_name: str, variable_manager: Optional[Any]) -> None: ...
    def get_loader(self) -> Optional[Any]: ...
    def get_plays(self) -> List[Any]: ...
