from typing import *

class Taggable:
    untagged = ... # type: frozenset
    _tags = ... # type: list

    def __init__(self) -> None: ...
    def _load_tags(self, attr: Any, ds: Any) -> List: ...
    def _get_attr_tags(self) -> List: ...
    def evaluate_tags(self, only_tags: Any, skip_tags: Any, all_vars: Any) -> bool: ...
